### ISSUE TITLE
When used in a header, formatted blocks do not inherit font size

### ISSUE THREAD

**Issue by connected-mhuanghobbs** [Adjective-Object/markdown-live#11]
See below:

![screen shot 2016-09-08 at 10 16 55 am](https://cloud.githubusercontent.com/assets/19578766/18352697/6d3eefc2-75ad-11e6-9b39-861ee6d13eb0.png)

**Comment by yariza** [comment]
https://github.com/Adjective-Object/markdown-live/pull/14
