### ISSUE TITLE
directory names overlap buttons when sidebar is collapsed

### ISSUE THREAD

**Issue by connected-mhuanghobbs** [Adjective-Object/markdown-live#8]
this can be fixed with a z-index on the buttons

![screen shot 2016-09-07 at 4 00 58 pm](https://cloud.githubusercontent.com/assets/19578766/18326556/538230c4-7514-11e6-8680-88eb1d10fe0f.png)

**Comment by yariza** [comment]
https://github.com/Adjective-Object/markdown-live/pull/13
